[package]
name = "hello_cargo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web3 = { git = "https://github.com/Plunderswap/rust-web3", branch = "graph-patches-onto-0.18", default-features = false, features = ["http", "http-rustls-tls"] }
tokio = { version = "1", features = ["full"] }